name: Build ASCIIGame with Webpack

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run C Tests

    steps:
      - uses: actions/checkout@v4

      - name: Install C dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-mixer-dev

      - name: Run all tests
        run: |
          make clean
          chmod +x run_tests.sh
          ./run_tests.sh

  build:
    runs-on: ubuntu-latest
    name: Build Full Application

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-mixer-dev

      - name: Install npm dependencies
        run: npm install

      - name: Build WASM game
        run: |
          make clean
          make all

      - name: Build frontend with Webpack
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: asciigame-full-build-node${{ matrix.node-version }}
          path: |
            dist/
            index/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: asciigame-full-build-node18.x

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
