name: Build ASCIIGame

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-mixer-dev

      - name: Run all tests
        run: |
          make clean
          chmod +x run_tests.sh
          ./run_tests.sh

      - name: Build native version
        run: |
          make native

  build-web:
    runs-on: ubuntu-latest
    name: Build WebAssembly

    steps:
      - uses: actions/checkout@v4

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest

      - name: Install SDL2 dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-mixer-dev

      - name: Build WebAssembly
        run: |
          make clean
          make all

      - name: Upload WebAssembly build
        uses: actions/upload-artifact@v4
        with:
          name: asciigame-wasm
          path: |
            index/
            !index/*.tmp

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./index
